name: OA source validator

on:
  workflow_dispatch:
    inputs:
      root_directory:
        description: 'Directory to process. Example: ./openaddresses/sources/us/va/'
        required: true
        default: './test'  # Default directory
jobs:
  run-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write  

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false 

      - name: Checkout the external repository
        uses: actions/checkout@v4
        with:
          repository: openaddresses/openaddresses
          path: openaddresses
          persist-credentials: false 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt

      - name: Run the Python script
        env:
          ROOT_DIRECTORY: ${{ github.event.inputs.root_directory }}
        run: |
          python src/main.py 

      - uses: actions/upload-artifact@v4
        with:
          name: logs
          path: out/*
      
      - name: Upload badges as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: badges
          path: ./badges/

      - name: Set up Git credentials
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Generate badges.json
        run: |
          ls badges/*.md | xargs -I {} basename {} > badge_list.txt
          echo "[" > badges.json
          awk '{printf "\"%s\",\n", $0}' badge_list.txt >> badges.json
          sed -i '$ s/,$//' badges.json
          echo "]" >> badges.json
        shell: bash
        
      - name: Move badges.json to gh-pages
        run: |
          mv badges.json badges/badges.json
        
      - name: Commit and push badges to gh-pages branch
        run: |
          git checkout -B gh-pages
          git add badges
          git commit -m "Update badges"
          git push -f origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
